export const VERIFICATION_EXIT_CODES = Object.freeze({
  ENV_MISSING: 20,
  ACCOUNT_MARKER_MISMATCH: 21,
  PUBLIC_READ_UNAUTHORIZED: 22,
  LIVE_WRITE_NOT_APPROVED: 23,
  RESTORE_FAILED: 24,
  ANALYTICS_CLEANUP_FAILED: 25,
  PUBLIC_API_TRANSPORT_ERROR: 30,
  PUBLIC_READ_FORBIDDEN: 31,
  PUBLIC_API_MALFORMED: 32,
  CONTROLLED_FIXTURE_REQUIRED: 33,
  PUBLIC_CAPABILITY_BOUNDARY_BROKEN: 34,
  SECURITY_PROOF_MISSING: 35,
  ANALYTICS_CANARY_REQUIRED: 36,
});

export const PROTECTED_REPORT_CODES = Object.freeze([
  "PROTECTED_RUN_COMPLETE",
  "PROTECTED_TEST_PASSED",
  "PROTECTED_TEST_FAILED",
  "PROTECTED_TEST_SKIPPED",
]);

export const PROTECTED_SETUP_CODES = Object.freeze([
  "ANALYTICS_RUN_CLEANUP_UNAVAILABLE",
  "RECOVERY_ARTIFACT_WRITE_FAILED",
  "ROUTE_FIXTURE_INVALID",
  "ROUTE_FIXTURE_COVERAGE_MISMATCH",
]);

export const STABLE_CHILD_CODES = new Set([
  ...Object.keys(VERIFICATION_EXIT_CODES),
  ...PROTECTED_REPORT_CODES,
  ...PROTECTED_SETUP_CODES,
]);

export const STABLE_BLOCKER_CODES = new Set(
  [...STABLE_CHILD_CODES].filter((code) => ![
    "PROTECTED_RUN_COMPLETE",
    "PROTECTED_TEST_PASSED",
    "PROTECTED_TEST_SKIPPED",
  ].includes(code)),
);
