import {describe,it,expect,vi,beforeEach} from 'vitest';
import {render,screen,waitFor,act,fireEvent} from '@testing-library/react';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import AddBookPage from '../AddBookPage';
import useAuthStore from '../../../../../store/store';
import {explorersApiClient} from '../../../../../lib/explorersApiClient';
import {emptyBookDetails} from '../../../../../../../tunes/shared/explorersBookContract';
const state=vi.hoisted(()=>({content:undefined as any}));
vi.mock('../../../api/useBooksOwnerContent',()=>({useBooksOwnerContent:()=>state.content}));
vi.mock('../../../../Favorites/components/TiptapEditor',()=>({default:({value,onChange}:any)=><textarea aria-label="Recommendation note" value={value} onChange={e=>onChange(e.target.value)}/>}));
vi.mock('../../../../../lib/explorersApiClient',()=>({explorersApiClient:{updateMyRecommendation:vi.fn(),getMyEditableRecommendation:vi.fn(),getCompleteMyCategoryTopPicks:vi.fn(),setMyCategoryTopPicks:vi.fn(),createMedia:vi.fn(),searchBookCandidates:vi.fn(),resolveBookEntity:vi.fn(),getMyEditableCollection:vi.fn(),createMyRecommendation:vi.fn(),importBookCovers:vi.fn()}}));
vi.mock('sonner',()=>({toast:{error:vi.fn(),success:vi.fn(),info:vi.fn()}}));
const observation={detail:{id:'rec',revision:1}};
const loaded=()=>({data:{bookLists:[{recommended_books:[{documentId:'rec',entity_id:'entity',title:'Hydrated book',authors:[],subjects:[],Media:[],volume_id:'volume',user_recommendation_note:'<p>Original</p>'}]}]},content:{observation:{generation:2},details:new Map([['rec',observation]])}});
function form(){return <MemoryRouter initialEntries={['/books/list/edit/rec']}><Routes><Route path="/books/:listId/edit/:bookId" element={<AddBookPage/>}/><Route path="/recommendations/books/:listId" element={<p>Saved list</p>}/></Routes></MemoryRouter>;}
describe('actual canonical Add/edit form',()=>{
 beforeEach(()=>{vi.clearAllMocks();useAuthStore.setState({generation:2,accountId:'owner'});state.content=loaded();vi.mocked(explorersApiClient.getMyEditableRecommendation).mockResolvedValue({detail:{id:'rec',revision:2}} as never);vi.mocked(explorersApiClient.getCompleteMyCategoryTopPicks).mockResolvedValue({topPicks:[]} as never);vi.stubGlobal('URL',Object.assign(URL,{createObjectURL:vi.fn(()=> 'blob:fixture'),revokeObjectURL:vi.fn()}));});
 it('holds interactive fields until hydration and saves captured revision',async()=>{state.content={};const view=render(form());expect(screen.queryByLabelText('Recommendation note')).toBeNull();state.content=loaded();view.rerender(form());fireEvent.change(await screen.findByLabelText('Recommendation note'),{target:{value:'<p>Edited</p>'}});fireEvent.click(screen.getByRole('button',{name:'Save Changes'}));await screen.findByText('Saved list');expect(explorersApiClient.updateMyRecommendation).toHaveBeenCalledWith(observation,expect.objectContaining({note:{version:1,format:'quill-html',html:'<p>Edited</p>'}}),expect.any(String),expect.any(AbortSignal));});
 it('retains draft on snapshot upload failure',async()=>{vi.mocked(explorersApiClient.createMedia).mockRejectedValue(new Error('Upload failed'));const view=render(form());fireEvent.change(await screen.findByLabelText('Recommendation note'),{target:{value:'Keep draft'}});fireEvent.change(view.container.querySelector('input[type=file]')!,{target:{files:[new File(['image'],'snapshot.png',{type:'image/png'})]}});fireEvent.click(screen.getByRole('button',{name:'Save Changes'}));await waitFor(()=>expect(explorersApiClient.createMedia).toHaveBeenCalled());expect(explorersApiClient.updateMyRecommendation).not.toHaveBeenCalled();expect(screen.getByLabelText('Recommendation note')).toHaveValue('Keep draft');expect(screen.queryByText('Saved list')).toBeNull();});
 it('aborts upload and clears old form when generation changes',async()=>{let resolveUpload:(value:any)=>void=()=>{};vi.mocked(explorersApiClient.createMedia).mockImplementation(()=>new Promise(resolve=>{resolveUpload=resolve;}));const view=render(form());await screen.findByLabelText('Recommendation note');fireEvent.change(view.container.querySelector('input[type=file]')!,{target:{files:[new File(['image'],'snapshot.png',{type:'image/png'})]}});fireEvent.click(screen.getByRole('button',{name:'Save Changes'}));await waitFor(()=>expect(explorersApiClient.createMedia).toHaveBeenCalled());const signal=vi.mocked(explorersApiClient.createMedia).mock.calls[0][2];await act(async()=>{useAuthStore.setState({generation:3,accountId:'other'});resolveUpload({id:'media'});});expect(signal?.aborted).toBe(true);expect(explorersApiClient.updateMyRecommendation).not.toHaveBeenCalled();expect(screen.queryByLabelText('Recommendation note')).toBeNull();expect(screen.queryByText('Saved list')).toBeNull();});
 it('reuses a partially created recommendation and saves current fields on retry',async()=>{
  vi.mocked(explorersApiClient.searchBookCandidates).mockResolvedValue({items:[{title:'Fixture',provider:'google_books',externalKind:'volume',externalId:'volume',preview:emptyBookDetails(),buyLinkSuggestion:null}],nextCursor:null} as never);
  vi.mocked(explorersApiClient.resolveBookEntity).mockResolvedValue({id:'entity'} as never);
  vi.mocked(explorersApiClient.getMyEditableCollection).mockResolvedValue({collection:{id:'list',revision:1}} as never);
  vi.mocked(explorersApiClient.createMyRecommendation).mockResolvedValue({id:'rec'} as never);
  vi.mocked(explorersApiClient.importBookCovers).mockResolvedValue({slots:{cover:{status:'copied'},thumbnail:{status:'copied'}}} as never);
  vi.mocked(explorersApiClient.setMyCategoryTopPicks).mockRejectedValueOnce(new Error('Pin conflict')).mockResolvedValue(undefined as never);
  render(<MemoryRouter initialEntries={['/books/list/add']}><Routes><Route path="/books/:listId/add" element={<AddBookPage/>}/><Route path="/recommendations/books/:listId" element={<p>Saved list</p>}/></Routes></MemoryRouter>);
  fireEvent.change(screen.getByPlaceholderText('Search by title, author, or ISBN...'),{target:{value:'fixture'}});fireEvent.click(await screen.findByRole('button',{name:/^Fixture/}));fireEvent.change(await screen.findByLabelText('Recommendation note'),{target:{value:'Initial draft'}});fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await waitFor(()=>expect(explorersApiClient.setMyCategoryTopPicks).toHaveBeenCalledTimes(1));await waitFor(()=>expect(screen.getByRole('button',{name:'Add to List'})).toBeEnabled());
  fireEvent.change(screen.getByLabelText('Recommendation note'),{target:{value:'Changed after failure'}});fireEvent.click(screen.getByRole('button',{name:'Add to List'}));await screen.findByText('Saved list');expect(explorersApiClient.createMyRecommendation).toHaveBeenCalledTimes(1);expect(explorersApiClient.updateMyRecommendation).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({note:{version:1,format:'quill-html',html:'Changed after failure'}}),expect.any(String),expect.any(AbortSignal));
 });
});
