import {describe,it,expect} from 'vitest';
import {createGameProviderCoordinator} from '../services/gameProviderBudget';
import {LIMITS} from '../services/gameCatalogTypes';
describe('Games process-owned budgets',()=>{
 it('holds64 callers and denies65th until actual release; double release cannot refund',()=>{const c=createGameProviderCoordinator({now:()=>0});const r=Array.from({length:64},()=>c.reserveCaller());expect(c.snapshot().callers).toBe(64);expect(()=>c.reserveCaller()).toThrow();r[0]();r[0]();expect(c.snapshot().callers).toBe(63);c.reserveCaller();r.slice(1).forEach(x=>x());});
 it('reserves physical copies before allocation and never negative',()=>{const c=createGameProviderCoordinator({now:()=>0});const r=c.reserveMemory(LIMITS.memory);expect(()=>c.reserveMemory(1)).toThrow();r();r();expect(c.snapshot().memory).toBe(0);for(const v of [0,-1,NaN,Infinity,1.1])expect(()=>c.reserveMemory(v)).toThrow();});
 it('counts failed starts sliding999/1000 and separates held native leases',()=>{let t=0;const c=createGameProviderCoordinator({now:()=>t});const r=Array.from({length:4},()=>c.reserveStart('catalog'));r.forEach(x=>x());expect(()=>c.reserveStart('catalog')).toThrow();t=999;expect(()=>c.reserveStart('catalog')).toThrow();t=1000;const held=Array.from({length:4},()=>c.reserveStart('catalog'));t=2000;Array.from({length:4},()=>c.reserveStart('catalog'));t=3000;expect(()=>c.reserveStart('catalog')).toThrow();held[0]();expect(c.snapshot().catalogNative).toBe(7);c.reserveStart('catalog');});
 it('binds exact credentials privately and rejects distinct set before native',()=>{const c=createGameProviderCoordinator({now:()=>0});c.bindCredentials({clientId:'fixture-id',clientSecret:'fixture-secret'});c.bindCredentials({clientId:'fixture-id',clientSecret:'fixture-secret'});expect(()=>c.bindCredentials({clientId:'other',clientSecret:'fixture-secret'})).toThrow(/unavailable/i);expect(()=>c.bindCredentials({clientId:'fixture-id',clientSecret:'other'})).toThrow(/unavailable/i);expect(JSON.stringify(c.snapshot())).not.toContain('fixture');});
 it('limits account execute and30 new commands; rate window cannot reset native ownership',()=>{let t=0;const c=createGameProviderCoordinator({now:()=>t});const r=c.reserveAccount('a');expect(()=>c.reserveAccount('a')).toThrow();for(let i=0;i<30;i++)c.rate('a');expect(()=>c.rate('a')).toThrow();t=60000;c.rate('a');expect(()=>c.reserveAccount('a')).toThrow();r();c.reserveAccount('a');});
});
