import {describe,it,expect,vi} from 'vitest';
import {createGameProviderCoordinator} from '../services/gameProviderBudget';
import {createGameProviderTransport,type NativeTarget,type NativeResponse,type Address} from '../services/gameProviderTransport';
import type {NativeOperation} from '../services/gameCatalogTypes';
const credentials={clientId:'fixture-id',clientSecret:'fixture-secret'};
const response=(json:unknown,status=200,headers:string[]=[]):NativeResponse=>({status,rawHeaders:['Content-Type','application/json',...headers],body:(async function*(){yield Buffer.from(JSON.stringify(json));})(),complete:()=>true});
const operation=(r:NativeResponse):NativeOperation<NativeResponse>=>({outcome:Promise.resolve(r),settled:Promise.resolve(),cancel:()=>{}});
const validToken={access_token:'synthetic-token',token_type:'bearer',expires_in:3600};
const fixture=(extra:Record<string,unknown>={})=>{let now=0;const c=createGameProviderCoordinator({now:()=>now});const targets:NativeTarget[]=[];const connect=vi.fn((t:NativeTarget)=>{targets.push(t);return operation(response(t.url.hostname==='id.twitch.tv'?validToken:[{id:42,name:'Game',total_rating:0,first_release_date:0}]));});const options={coordinator:c,credentials,now:()=>now,resolve:async()=>[{address:'8.8.8.8',family:4}],connect,...extra};return {c,targets,connect,options,clock:(n:number)=>now=n};};
describe('Games token/native transport',()=>{
 it('shares one token flight across ten callers with truthful four starts and no hidden queue',async()=>{const f=fixture();const a=createGameProviderTransport(f.options);const b=createGameProviderTransport(f.options);const jobs=Array.from({length:10},(_,i)=>(i%2?a:b).catalog('fixed-fixture-query',new AbortController().signal));const result=await Promise.allSettled(jobs.map(x=>x.outcome));await Promise.all(jobs.map(x=>x.settled));expect(f.targets.filter(t=>t.url.hostname==='id.twitch.tv')).toHaveLength(1);expect(f.targets.filter(t=>t.url.hostname==='api.igdb.com')).toHaveLength(4);expect(result.filter(x=>x.status==='fulfilled')).toHaveLength(4);expect(result.filter(x=>x.status==='rejected')).toHaveLength(6);expect(f.c.snapshot().catalogNative).toBe(0);});
 it('rejects distinct credentials before cached/inflight attachment and never emits fingerprint',async()=>{const f=fixture();const t=createGameProviderTransport(f.options);const op=t.catalog('q',new AbortController().signal);await op.outcome;await op.settled;expect(()=>createGameProviderTransport({...f.options,credentials:{...credentials,clientSecret:'other'}})).toThrow(/unavailable/i);expect(f.connect).toHaveBeenCalledTimes(2);expect(JSON.stringify(f.c.snapshot())).not.toContain('fixture');});
 it.each(['127.0.0.1','10.0.0.1','169.254.169.254','::1','::ffff:8.8.8.8','fe80::1'])('denies private or mapped DNS %s before request creation',async(address)=>{const f=fixture({resolve:async()=>[{address,family:address.includes(':')?6:4}]});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toMatchObject({status:503});await op.settled;expect(f.connect).not.toHaveBeenCalled();});
 it('denies mixed answers and65 records',async()=>{for(const addresses of [[{address:'8.8.8.8',family:4},{address:'10.0.0.1',family:4}],Array.from({length:65},()=>({address:'8.8.8.8',family:4}))]){const f=fixture({resolve:async()=>addresses});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toThrow();await op.settled;expect(f.connect).not.toHaveBeenCalled();}});
 it('caller timeout retains pending lookup lease and blocks replacement refresh until true late DNS settlement',async()=>{let finish!:(v:Address[])=>void;const f=fixture({phaseMs:15,resolve:()=>new Promise<Address[]>(r=>finish=r)});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toMatchObject({status:503});expect(f.c.snapshot().tokenNative).toBe(1);expect(f.c.snapshot().memory).toBeGreaterThan(0);let settled=false;void op.settled.then(()=>settled=true);await Promise.resolve();expect(settled).toBe(false);finish([{address:'8.8.8.8',family:4}]);await op.settled;expect(f.connect).not.toHaveBeenCalled();expect(f.c.snapshot().tokenNative).toBe(0);expect(f.c.snapshot().memory).toBe(0);});
 it('fixed URLs own headers and secrets stay out of URL/DTO',async()=>{const f=fixture();const op=createGameProviderTransport(f.options).catalog('fixed query',new AbortController().signal);const rows=await op.outcome;await op.settled;expect(f.targets[0].url.href).toBe('https://id.twitch.tv/oauth2/token');expect(f.targets[0].body).toContain('grant_type=client_credentials');expect(f.targets[1].url.href).toBe('https://api.igdb.com/v4/games');expect(f.targets[1].headers['Client-ID']).toBe(credentials.clientId);expect(f.targets[1].headers.Authorization).toBe('Bearer synthetic-token');expect(JSON.stringify(rows)).not.toMatch(/fixture-secret|synthetic-token/);});
 it.each([{...validToken,expires_in:0},{...validToken,token_type:'basic'},{...validToken,access_token:'a'.repeat(4097)},{...validToken,extra:'credential'}])('rejects malformed token without catalog start',async(token)=>{const f=fixture({connect:vi.fn(()=>operation(response(token)))});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toMatchObject({status:502});await op.settled;expect(f.c.snapshot().memory).toBe(0);});
 it('preserves first body-limit failure through stalled settlement',async()=>{let done!:()=>void;const closure=new Promise<void>(r=>done=r);const f=fixture({phaseMs:30,connect:()=>({outcome:Promise.resolve({status:200,rawHeaders:['Content-Type','application/json'],body:(async function*(){yield Buffer.alloc(65537);})(),complete:()=>true}),settled:closure,cancel:()=>{}})});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toMatchObject({code:'PROVIDER_INVALID_RESPONSE'});expect(f.c.snapshot().memory).toBeGreaterThan(0);done();await op.settled;expect(f.c.snapshot().memory).toBe(0);});
 it('401 invalidates token and only explicit next call refreshes;429 is not empty success',async()=>{let calls=0;const f=fixture({connect:(t:NativeTarget)=>operation(response(t.url.hostname==='id.twitch.tv'?validToken:[],t.url.hostname==='id.twitch.tv'?200:++calls===1?401:429,['Retry-After','2']))});const t=createGameProviderTransport(f.options);const one=t.catalog('q',new AbortController().signal);await expect(one.outcome).rejects.toMatchObject({status:503});await one.settled;f.clock(1000);const two=t.catalog('q',new AbortController().signal);await expect(two.outcome).rejects.toMatchObject({status:429,retryAfterSeconds:2});await two.settled;expect(calls).toBe(2);});
 /*
  * Ticket 4.2:42's `provider_429_is_recoverable`, verbatim so a grep finds an assertion
  * rather than documentation. The case above covers the *classification* half - a 429 is
  * reported with its Retry-After instead of being swallowed as an empty success. This is
  * the recovery half, which nothing drove end to end.
  *
  * The assertion that carries it is the last one: a 429 must **not** invalidate the cached
  * token, so only one token flight happens across both calls. That is what separates a
  * recoverable rate limit from a 401, which the case above shows *does* invalidate. Without
  * it a rate-limited caller would burn a token refresh on every retry and convert a
  * transient 429 into sustained credential traffic.
  */
 it('provider_429_is_recoverable',async()=>{let catalogCalls=0,tokenCalls=0;const f=fixture({connect:(t:NativeTarget)=>t.url.hostname==='id.twitch.tv'?(++tokenCalls,operation(response(validToken))):++catalogCalls===1?operation(response([],429,['Retry-After','2'])):operation(response([{id:42,name:'Game',total_rating:0,first_release_date:0}]))});const t=createGameProviderTransport(f.options);const first=t.catalog('q',new AbortController().signal);await expect(first.outcome).rejects.toMatchObject({status:429,retryAfterSeconds:2});await first.settled;f.clock(3000);const second=t.catalog('q',new AbortController().signal);const rows=await second.outcome;await second.settled;expect(rows).toHaveLength(1);expect(catalogCalls).toBe(2);expect(tokenCalls).toBe(1);});
});

// Additional bounded authority/cancellation regressions use the same private fixture constructors above.
describe('Games transport authority edge cases',()=>{
 it('inflight credential mismatch denies before second native or waiter',async()=>{let release!:(r:NativeResponse)=>void;const f=fixture({connect:()=>({outcome:new Promise<NativeResponse>(r=>release=r),settled:Promise.resolve(),cancel:()=>{}})});const first=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await new Promise<void>(r=>setImmediate(r));expect(()=>createGameProviderTransport({...f.options,credentials:{...credentials,clientId:'different'}})).toThrow(/unavailable/i);release(response(validToken));await new Promise<void>(r=>setImmediate(r));release(response([]));await first.outcome;await first.settled;});
 it('32 waiter cap is finite and33rd fails before attaching; one cancellation keeps shared refresh alive',async()=>{let tokenReady!:(r:NativeResponse)=>void;let cancelled=0;const f=fixture({connect:(t:NativeTarget)=>t.url.hostname==='id.twitch.tv'?{outcome:new Promise<NativeResponse>(r=>tokenReady=r),settled:Promise.resolve(),cancel:()=>cancelled++}:operation(response([]))});const t=createGameProviderTransport(f.options),controllers=Array.from({length:33},()=>new AbortController());const ops=controllers.map(c=>t.catalog('q',c.signal));const result=Promise.allSettled(ops.map(x=>x.outcome));await new Promise<void>(r=>setImmediate(r));controllers[0].abort();await new Promise<void>(r=>setImmediate(r));expect(cancelled).toBe(0);tokenReady(response(validToken));const values=await result;await Promise.all(ops.map(x=>x.settled));expect(values.filter(x=>x.status==='fulfilled')).toHaveLength(4);expect(values.filter(x=>x.status==='rejected')).toHaveLength(29);});
 it('old401 cannot invalidate newer token generation',async()=>{let rejectOld!:(r:NativeResponse)=>void;let tokenCalls=0,catalogCalls=0;const f=fixture({connect:(t:NativeTarget)=>{if(t.url.hostname==='id.twitch.tv')return operation(response({...validToken,access_token:`token${++tokenCalls}`}));catalogCalls++;return catalogCalls===1?{outcome:new Promise<NativeResponse>(r=>rejectOld=r),settled:Promise.resolve(),cancel:()=>{}}:operation(response([]));}});const t=createGameProviderTransport(f.options);const old=t.catalog('old',new AbortController().signal);await new Promise<void>(r=>setImmediate(r));f.clock(3600000);const fresh=t.catalog('fresh',new AbortController().signal);await fresh.outcome;await fresh.settled;rejectOld(response([],401));await expect(old.outcome).rejects.toMatchObject({status:503});await old.settled;const next=t.catalog('next',new AbortController().signal);await next.outcome;await next.settled;expect(tokenCalls).toBe(2);});
 it.each([['Content-Type','text/plain'],['Content-Type','application/json','Content-Length','65537'],['Content-Type','application/json','Content-Encoding','gzip'],['Content-Type','application/json','Content-Length','1','content-length','1']])('rejects invalid headers %j without empty success',async(rawHeaders)=>{const f=fixture({connect:()=>operation({...response(validToken),rawHeaders})});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toMatchObject({status:502});await op.settled;});
 it('strict token duplicate escaped keys and invalid UTF8 denied',async()=>{for(const bytes of [Buffer.from('{"access_token":"a","access\\u005ftoken":"b","token_type":"bearer","expires_in":3600}'),Buffer.from([255])]){const f=fixture({connect:()=>operation({...response(validToken),body:(async function*(){yield bytes;})()})});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toMatchObject({status:502});await op.settled;}});
 it('missing credentials deny before lookup and request creation',()=>{const f=fixture();expect(()=>createGameProviderTransport({...f.options,credentials:{clientId:'',clientSecret:''}})).toThrow(/unavailable/i);expect(f.connect).not.toHaveBeenCalled();});
});
it('retains token-cache memory after request settlement and releases matching401 exactly once',async()=>{let status=200;const f=fixture({connect:(t:NativeTarget)=>operation(response(t.url.hostname==='id.twitch.tv'?validToken:[],t.url.hostname==='id.twitch.tv'?200:status))});const t=createGameProviderTransport(f.options);const first=t.catalog('q',new AbortController().signal);await first.outcome;await first.settled;const retained=f.c.snapshot().memory;f.clock(1000);status=401;const second=t.catalog('q',new AbortController().signal);await expect(second.outcome).rejects.toMatchObject({status:503});await second.settled;expect(retained).toBeGreaterThan(0);expect(f.c.snapshot().memory).toBe(0);});
it('raw resolver/socket errors never escape fixed provider failure',async()=>{const f=fixture({resolve:async()=>{throw new Error('synthetic-secret-native-host');}});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);const error=await op.outcome.catch(e=>e);await op.settled;expect(error).toMatchObject({status:503,code:'PROVIDER_UNAVAILABLE'});expect(String(error)).not.toContain('synthetic-secret');});
it('independent runtime fixture DNS/token boundaries and64KiB envelope are enforced',async()=>{const {readFileSync}=await import('node:fs');const cases=JSON.parse(readFileSync(new URL('./contracts/fixtures/igdb-runtime/cases.json',import.meta.url),'utf8'));for(const d of cases.dns){const f=fixture({resolve:async()=>[{address:d.address,family:d.family}]});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);if(d.admitted)await expect(op.outcome).resolves.toHaveLength(1);else await expect(op.outcome).rejects.toMatchObject({status:503});await op.settled;expect(f.connect.mock.calls.length).toBe(d.admitted?2:0);}for(const v of cases.token){const f=fixture({connect:(t:NativeTarget)=>operation(response(t.url.hostname==='id.twitch.tv'?{...validToken,expires_in:v.expires}:[]))});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);if(v.status===200)await expect(op.outcome).resolves.toEqual([]);else await expect(op.outcome).rejects.toMatchObject({status:v.status});await op.settled;}for(const count of cases.catalogEnvelope){const json=JSON.stringify([{id:1,name:'Game'}]);const body=Buffer.from(json+' '.repeat(count-Buffer.byteLength(json)));const f=fixture({connect:(t:NativeTarget)=>operation(t.url.hostname==='id.twitch.tv'?response(validToken):{...response([]),body:(async function*(){yield body;})()})});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);if(count===65536)await expect(op.outcome).resolves.toHaveLength(1);else await expect(op.outcome).rejects.toMatchObject({status:502});await op.settled;}});
it('stalled body read quarantines physical/native capacity after deadline until real read settles',async()=>{let end!:()=>void;const wait=new Promise<void>(r=>end=r);const f=fixture({phaseMs:15,connect:(t:NativeTarget)=>operation(t.url.hostname==='id.twitch.tv'?response(validToken):{...response([]),body:(async function*(){await wait;yield Buffer.from('[]');})()})});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal);await expect(op.outcome).rejects.toMatchObject({status:503});expect(f.c.snapshot().catalogNative).toBe(1);expect(f.c.snapshot().memory).toBeGreaterThanOrEqual(4*1024*1024);end();await op.settled;expect(f.c.snapshot().catalogNative).toBe(0);expect(f.c.snapshot().memory).toBeLessThan(10000);});
it('cancelled sole token waiter cannot publish late token or start replacement before native closure',async()=>{let release!:(r:NativeResponse)=>void,close!:()=>void;const closure=new Promise<void>(r=>close=r);const f=fixture({connect:()=>({outcome:new Promise<NativeResponse>(r=>release=r),settled:closure,cancel:()=>{}})});const c=new AbortController(),t=createGameProviderTransport(f.options),op=t.catalog('q',c.signal);const rejected=expect(op.outcome).rejects.toMatchObject({status:503});await new Promise<void>(r=>setImmediate(r));c.abort();await rejected;const second=t.catalog('q',new AbortController().signal);await expect(second.outcome).rejects.toMatchObject({status:503});expect(f.c.snapshot().tokenNative).toBe(1);release(response(validToken));close();await Promise.all([op.settled,second.settled]);expect(f.c.snapshot().memory).toBe(0);expect(f.c.snapshot().tokenNative).toBe(0);});
it('expired token from a fulfilled but unsettled refresh flight cannot authorize a later catalog request',async()=>{let close!:()=>void;const held=new Promise<void>(r=>close=r);let catalogs=0;const f=fixture({connect:(t:NativeTarget)=>t.url.hostname==='id.twitch.tv'?{outcome:Promise.resolve(response({...validToken,expires_in:31})),settled:held,cancel:()=>{}}:((catalogs++,operation(response([]))))});const t=createGameProviderTransport(f.options);const first=t.catalog('one',new AbortController().signal);await first.outcome;f.clock(2000);const second=t.catalog('two',new AbortController().signal);const value=await second.outcome.then(()=>({status:200}),e=>e);close();await Promise.all([first.settled,second.settled]);expect(value).toMatchObject({status:429,code:'PROVIDER_BUSY'});expect(catalogs).toBe(1);});
it('token expiring during fresh Actor wait cannot start catalog native bytes',async()=>{const f=fixture({connect:(t:NativeTarget)=>operation(response(t.url.hostname==='id.twitch.tv'?{...validToken,expires_in:31}:[]))});const op=createGameProviderTransport(f.options).catalog('q',new AbortController().signal,{beforeStart:async()=>{f.clock(2000);},onStart:()=>{}});const value=await op.outcome.then(()=>({status:200}),e=>e);await op.settled;expect(value).toMatchObject({status:503});expect(f.targets.filter(t=>t.url.hostname==='api.igdb.com')).toHaveLength(0);});
