import type {EditableOwnerRecommendation,OwnerCollectionDto,OwnerMembershipDto} from '../../../../../tunes/shared/explorersOwnerContentContract';
import {emptyMovieDetails} from '../../../../../tunes/shared/explorersMovieContract';
import type {MovieList,RecommendedMovie} from '../types';
type Pin={recommendationId:string;collectionId:string;position:number};
export function movieViewModel(detail:Readonly<EditableOwnerRecommendation>,membership:Readonly<OwnerMembershipDto>,pin?:Readonly<Pin>):RecommendedMovie{
 const facts=detail.effectiveMovieDetails??emptyMovieDetails(),provenance='provenance' in detail.entity?detail.entity.provenance:null,context=detail.movieContext??{region:'US',selectedProviderIds:null};
 const region=facts.watchProviders[context.region],seen=new Set<number>();const offers=region?[...region.flatrate,...region.rent,...region.buy].filter(p=>{if(seen.has(p.providerId))return false;seen.add(p.providerId);return true;}):[];
 const selected=context.selectedProviderIds===null?offers.sort((a,b)=>a.priority-b.priority).slice(0,8):context.selectedProviderIds.map(id=>{const p=offers.find(p=>p.providerId===id);if(!p)throw Error('Movie provider context unavailable');return p;});
 return {documentId:detail.id,entity_id:detail.entityId,tmdb_id:provenance?.externalId??'',media_type:facts.mediaType==='movie'?'Movie':'TV',title:detail.displayTitle??'Untitled movie',original_title:facts.originalTitle,year:facts.yearText,
 poster_path:detail.providerMedia?.poster?.url??facts.posterUrl,backdrop_path:detail.providerMedia?.backdrop?.url??facts.backdropUrl,genres:facts.genres.map(g=>({id:g.providerGenreId,name:g.name})),director:facts.director,runtime:facts.runtimeMinutes,tmdb_rating:facts.providerRating,overview:facts.overview,season_count:facts.seasonCount,
 user_recommendation_note:detail.note?.html??'',user_rating:detail.userRating,watch_providers:selected.map(p=>({provider_id:p.providerId,provider_name:p.name,logo_path:p.logoUrl,...(region?.link?{link:region.link}:{})})),
 cast_details:facts.cast.slice(0,10).map((c,ordinal)=>({original_name:c.name,character:c.character,profile_url:detail.providerMedia?.cast.find(x=>x.slot.ordinal===ordinal)?.media?.url??c.profileUrl})),is_pinned:!!pin,pin_order:pin?.position??null,display_order:membership.displayOrder,
 Media:detail.mediaIds.map(id=>({documentId:id,url:`/api/explorers/v1/media/${id}/content`})),media_details:null,movie_list:{documentId:membership.collectionId,List_Name:'',slug:''},movie_categories:(detail.movieTerms??[]).map(t=>({documentId:t.id,genre_name:t.label,slug:t.slug}))};
}
export function collectionViewModel(collection:Readonly<OwnerCollectionDto>,movies:RecommendedMovie[],username=''):MovieList{return {documentId:collection.id,List_Name:collection.title,list_description:collection.description,slug:collection.slug,Visibility:collection.visibility==='public'&&collection.publicationState==='published',cover_image:collection.coverMediaId?{documentId:collection.coverMediaId,url:`/api/explorers/v1/media/${collection.coverMediaId}/content`}:null,display_order:collection.displayOrder,top_picks_heading:collection.heading,recommended_movies:movies.map(m=>({...m,movie_list:{documentId:collection.id,List_Name:collection.title,slug:collection.slug}})),account:{documentId:collection.accountId,username}};}
