import {assertFixtureOrigin} from './proxy-fixture-authority.mjs';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {test,expect,type Page,type BrowserContext,type APIRequestContext} from '@playwright/test';
type Persona={userId:string;cookie:string;handle:string};
const fixture=JSON.parse(readFileSync(process.env.GAMES_E2E_FIXTURE_PATH!,'utf8')) as {origin:string;controlCapability:string;personas:{ownerA:Persona;ownerB:Persona}};
assertFixtureOrigin(fixture);if(fixture.origin!==process.env.PLAYWRIGHT_EXTERNAL_BASE_URL)throw Error('Games fixture origin mismatch');
const base='/api/explorers/v1';
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLttAAAAABJRU5ErkJggg==','base64');
async function cookies(context:BrowserContext,owner:Persona){const i=owner.cookie.indexOf('=');await context.addCookies([{name:owner.cookie.slice(0,i),value:owner.cookie.slice(i+1),url:fixture.origin,sameSite:'Lax'}]);}
async function signIn(page:Page,owner=fixture.personas.ownerA){await cookies(page.context(),owner);await page.route('**/*',r=>{const u=new URL(r.request().url());return u.origin===fixture.origin||['data:','blob:'].includes(u.protocol)?r.continue():r.abort();});const me=await page.request.get(`${base}/me`);expect(me.status()).toBe(200);const account=(await me.json()).account;expect(account.id).not.toBe(owner.userId);return account;}
async function command(api:APIRequestContext,method:'post'|'patch'|'put'|'delete',path:string,data:unknown,key=randomUUID()){return api[method](`${base}${path}`,{headers:{Origin:fixture.origin,'Idempotency-Key':key},data});}
async function editable(api:APIRequestContext,kind:'collections'|'recommendations',id:string){const r=await api.get(`${base}/${kind}/${id}/editable`);expect(r.status()).toBe(200);return (await r.json())[kind==='collections'?'collection':'recommendation'];}
async function createList(api:APIRequestContext,title:string){const r=await command(api,'post','/collections',{category:'games',title,slug:`uat-${randomUUID()}`,visibility:'private',publicationState:'draft'});expect(r.status()).toBe(201);return (await r.json()).collection;}
async function manual(api:APIRequestContext,list:any,title:string,mediaIds:string[]=[]){const e=await command(api,'post','/entities/resolve',{kind:'manual',category:'games',details:{title}});expect(e.status()).toBe(200);const parent=await editable(api,'collections',list.id);const r=await command(api,'post','/recommendations',{category:'games',collectionId:list.id,expectedCollectionRevision:parent.revision,entityId:(await e.json()).entity.id,mediaIds,userRating:null,publicationState:'draft'});expect(r.status()).toBe(201);return (await r.json()).recommendation;}
async function publish(api:APIRequestContext,list:any,row:any){let observed=await editable(api,'collections',list.id);expect((await command(api,'patch',`/collections/${list.id}`,{expectedRevision:observed.revision,visibility:'public',publicationState:'published'})).status()).toBe(200);observed=await editable(api,'recommendations',row.id);expect((await command(api,'patch',`/recommendations/${row.id}`,{expectedRevision:observed.revision,publicationState:'published'})).status()).toBe(200);}
async function form(page:Page,list:any){await page.goto(`/recommendations/games/${list.id}/add`);await expect(page.getByLabel('Game title',{exact:true})).toBeVisible();}
async function save(page:Page,title:string){await page.getByLabel('Game title',{exact:true}).fill(title);const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===`${base}/recommendations`);await page.getByRole('button',{name:'Save game',exact:true}).click();expect((await response).status()).toBe(201);return (await (await response).json()).recommendation;}
function monitor(page:Page){const bad:string[]=[];page.on('request',r=>{if(/legacy-rest.invalid|api\.igdb\.com|id\.twitch\.tv|oauth2\/token|\/igdb-api|\/twitch-api/.test(r.url())||/graphql/.test(r.url())&&/GameLists|GamesByList|RecommendedGame|MyAccountForGames/.test(r.postData()??''))bad.push('forbidden-provider-or-legacy-request');});return bad;}
async function complete(api:APIRequestContext,path:string,key:'gameLists'|'recommendations'){const rows:any[]=[];let cursor:string|null=null;let pages=0;do{const r=await api.get(path+(cursor?'?cursor='+encodeURIComponent(cursor):''));expect(r.status()).toBe(200);const data=await r.json();const page=key==='recommendations'?data.gameLists[0]:data;rows.push(...page[key]);cursor=page.nextCursor;expect(cursor===null||typeof cursor==='string').toBe(true);expect(++pages).toBeLessThan(25);}while(cursor);return rows;}

async function continueVisible(page:Page,label:string,title:string){const target=page.getByText(title,{exact:true}).first();for(let attempt=0;attempt<6&&!await target.isVisible();attempt++){await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));const more=page.getByRole('button',{name:label,exact:true});await expect(target.or(more).first()).toBeVisible();if(await target.isVisible())break;await more.scrollIntoViewIfNeeded();try{await more.click({timeout:2000});}catch(error){if(!await target.isVisible()&&await more.count())throw error;}}await expect(target).toBeVisible();}

const publicCaseTitles=["Games manual: Home creates a native list and distinct same-title recommendations","Games manual: note and creator rating survive edit and reload without provider facts","Games manual: complete owner pages preserve memberships reorder and pin position zero","Games manual: Keep draft and Publish preserve keyboard decision and public state","Games manual: ready uploaded cover and gallery bytes enforce owner public and foreign attachment","Games manual: provider unavailable preserves draft and forbids browser credential authority","Games manual: anonymous category and list continuation reveal later rows and terminal state","Games manual: ancestor hide archive and suspension deny fresh and inflight public bytes","Games manual: two anonymous contexts and username transition never reuse private or late rows","Games manual: account and route changes fence every deferred save continuation"];
function publicCaseTag(info:{project:{name:string};title:string}){const project=info.project.name==='games-desktop'?'desktop':info.project.name==='games-mobile'?'mobile':undefined,index=publicCaseTitles.indexOf(info.title);if(!project||index<0)throw Error('Unknown public case identity');return project+'-'+index;}
test.beforeEach(async({page},info)=>{const bodyTimeout=info.timeout,started=performance.now();const response=await page.request.post('/api/__games-fixture/control',{headers:{Origin:fixture.origin,'x-games-fixture-capability':fixture.controlCapability},data:{action:'public-begin-'+publicCaseTag(info)},timeout:80000});const elapsed=Math.ceil(performance.now()-started);expect(response.status()).toBe(200);const receipt=await response.json();expect(Number.isInteger(receipt.waitMs)&&receipt.waitMs>=0&&receipt.waitMs<75000).toBe(true);expect(elapsed).toBeLessThan(80000);info.setTimeout(bodyTimeout+elapsed);});
test.afterEach(async({page},info)=>{const response=await page.request.post('/api/__games-fixture/control',{headers:{Origin:fixture.origin,'x-games-fixture-capability':fixture.controlCapability},data:{action:'public-end-'+publicCaseTag(info)},timeout:20000});expect(response.status()).toBe(200);});

test('Games manual: Home creates a native list and distinct same-title recommendations',async({page},info)=>{
 await signIn(page);const bad=monitor(page);await page.goto('/recommendations/games');await page.getByRole('button',{name:'New List',exact:true}).filter({visible:true}).first().click();await page.locator('input[name="List_Name"]').fill(`Browser ${info.project.name}`);const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===`${base}/collections`);await page.getByRole('button',{name:'Create List',exact:true}).click();expect((await response).status()).toBe(201);const list=(await (await response).json()).collection;
 const ids:string[]=[];for(let n=0;n<2;n++){await form(page,list);const row=await save(page,'Same editorial title');ids.push(row.id);await expect(page).toHaveURL(new RegExp(`/recommendations/games/${list.id}$`));}expect(new Set(ids).size).toBe(2);await page.reload();await expect(page.getByText('Same editorial title',{exact:true})).toHaveCount(2);for(const id of ids){const detail=await editable(page.request,'recommendations',id);expect(detail.gamePresentation).toMatchObject({origin:'manual',providerExternalId:null,providerFacts:null});}expect(bad).toEqual([]);
});

test('Games manual: note and creator rating survive edit and reload without provider facts',async({page})=>{
 await signIn(page);const list=await createList(page.request,'Edit roundtrip');await form(page,list);await page.getByRole('combobox',{name:'Your rating',exact:true}).selectOption('8');await page.locator('[contenteditable=true]').fill('Native rich note 😀');const row=await save(page,'Manual edit');const initial=await editable(page.request,'recommendations',row.id);expect(initial.userRating).toBe(8);expect(initial.note.html.replaceAll('&nbsp;',' ')).toContain('Native rich note 😀');await page.goto(`/recommendations/games/${list.id}/edit/${row.id}`);await expect(page.getByLabel('Game title',{exact:true})).toHaveValue('Manual edit');await expect(page.getByRole('combobox',{name:'Your rating',exact:true})).toHaveValue('8');await page.getByRole('combobox',{name:'Your rating',exact:true}).selectOption('');await page.locator('[contenteditable=true]').fill('Revised note 😀');const patched=page.waitForResponse(r=>r.request().method()==='PATCH'&&new URL(r.url()).pathname===`${base}/recommendations/${row.id}`);await page.getByRole('button',{name:'Save game',exact:true}).click();expect((await patched).status()).toBe(200);await page.reload();const detail=await editable(page.request,'recommendations',row.id);expect(detail.userRating).toBeNull();expect(detail.note.html.replaceAll('&nbsp;',' ')).toContain('Revised note 😀');expect(detail.gamePresentation.providerFacts).toBeNull();
});

test('Games manual: complete owner pages preserve memberships reorder and pin position zero',async({page})=>{
 await signIn(page,fixture.personas.ownerB);await page.goto('/recommendations/games');const collectionReply=await page.request.get(`${base}/collections?category=games&limit=100`);expect(collectionReply.status()).toBe(200);const lists=(await collectionReply.json()).items;const first=lists.find((x:any)=>x.slug==='seed-list-0');await page.goto(`/recommendations/games/${first.id}`);await expect(page.getByText('ownerB seed game 0-29',{exact:true})).toBeVisible();const pins=await (await page.request.get(`${base}/categories/games/top-picks?limit=100`)).json();expect(pins.items).toHaveLength(15);expect(pins.items[0].position).toBe(0);
 const second=await createList(page.request,'Secondary membership');const item=await editable(page.request,'recommendations',pins.items[0].recommendationId),parent=await editable(page.request,'collections',second.id);const body={expectedCollectionRevision:parent.revision,expectedRecommendationRevision:item.revision},key=randomUUID(),path=`/collections/${second.id}/memberships/${item.id}`;const attached=await command(page.request,'post',path,body,key);expect(attached.status()).toBe(200);expect(await (await command(page.request,'post',path,body,key)).json()).toEqual(await attached.json());const sibling=await manual(page.request,second,'Membership reorder sibling');const latestParent=await editable(page.request,'collections',second.id);expect((await command(page.request,'patch',`/collections/${second.id}/order`,{expectedRevision:latestParent.revision,orderedRecommendationIds:[sibling.id,item.id]})).status()).toBe(200);await page.reload();await page.goto(`/recommendations/games/${second.id}`);await expect(page.getByText('ownerB seed game 0-0',{exact:true})).toBeVisible();await publish(page.request,second,item);const publicSecond=await page.request.get(`${base}/profiles/${fixture.personas.ownerB.handle}/recommendations/games/${second.slug}`);expect(publicSecond.status()).toBe(200);expect((await publicSecond.json()).gameLists[0].recommendations.find((x:any)=>x.id===item.id).pinPosition).toBeNull();const detached=await command(page.request,'delete',path,{expectedCollectionRevision:(await editable(page.request,'collections',second.id)).revision,expectedRecommendationRevision:(await editable(page.request,'recommendations',item.id)).revision});expect(detached.status()).toBe(200);expect((await (await page.request.get(`${base}/categories/games/top-picks?limit=100`)).json()).items[0]).toMatchObject({recommendationId:item.id,collectionId:first.id,position:0});
});

test('Games manual: Keep draft and Publish preserve keyboard decision and public state',async({page,browser})=>{
 await signIn(page);const list=await createList(page.request,'Explicit publication'),row=await manual(page.request,list,'Separate publication');const observed=await editable(page.request,'collections',list.id);expect((await command(page.request,'patch',`/collections/${list.id}`,{expectedRevision:observed.revision,visibility:'public',publicationState:'published'})).status()).toBe(200);const anonymous=await browser.newContext({baseURL:fixture.origin});try{const path=`${base}/profiles/${fixture.personas.ownerA.handle}/recommendations/games/${list.slug}`;expect(JSON.stringify(await (await anonymous.request.get(path)).json())).not.toContain('Separate publication');await page.goto(`/recommendations/games/${list.id}`);const button=page.getByRole('button',{name:'Publish Separate publication',exact:true});await button.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Keep Separate publication as draft',exact:true})).toBeVisible();expect((await editable(page.request,'recommendations',row.id)).publicationState).toBe('published');expect(JSON.stringify(await (await anonymous.request.get(path)).json())).toContain('Separate publication');await page.reload();await page.getByRole('button',{name:'Keep Separate publication as draft',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Publish Separate publication',exact:true})).toBeVisible();expect(JSON.stringify(await (await anonymous.request.get(path)).json())).not.toContain('Separate publication');let completed:(()=>void)|undefined;const acknowledged=new Promise<void>(done=>{completed=done;}),keys:string[]=[];let dropped=false;const target=`**/api/explorers/v1/recommendations/${row.id}`;await page.route(target,async route=>{if(route.request().method()!=='PATCH')return route.continue();keys.push(route.request().headers()['idempotency-key']);if(!dropped){dropped=true;const response=await route.fetch();expect(response.status()).toBe(200);completed?.();await route.abort('failed');}else await route.continue();});await page.getByRole('button',{name:'Publish Separate publication',exact:true}).click();await acknowledged;await expect(page.getByRole('button',{name:'Publish Separate publication',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Publish Separate publication',exact:true}).click();await expect(page.getByRole('button',{name:'Keep Separate publication as draft',exact:true})).toBeVisible();expect(keys).toHaveLength(2);expect(keys[0]).toBeTruthy();expect(keys[1]).toBe(keys[0]);await page.unroute(target);}finally{await anonymous.close();}
});

test('Games manual: ready uploaded cover and gallery bytes enforce owner public and foreign attachment',async({page,browser})=>{
 await signIn(page);const list=await createList(page.request,'Uploaded media');await form(page,list);const uploaded: string[]=[];page.on('response',async r=>{if(r.request().method()==='POST'&&new URL(r.url()).pathname===`${base}/media`&&r.status()===201)uploaded.push((await r.json()).media.id);});let releaseUpload:(()=>void)|undefined,enteredUpload:(()=>void)|undefined;const uploadGate=new Promise<void>(done=>{releaseUpload=done;}),uploadStarted=new Promise<void>(done=>{enteredUpload=done;});await page.route('**/api/explorers/v1/media',async route=>{const response=await route.fetch();expect(response.status()).toBe(201);enteredUpload?.();await uploadGate;await route.fulfill({response});});await page.locator('input[type=file]').setInputFiles([{name:'cover.png',mimeType:'image/png',buffer:png},{name:'gallery.png',mimeType:'image/png',buffer:png}]);await uploadStarted;await expect(page.getByRole('button',{name:'Save game',exact:true})).toBeDisabled();releaseUpload?.();await expect(page.getByRole('button',{name:'Remove snapshot',exact:true})).toHaveCount(2);await page.unroute('**/api/explorers/v1/media');const row=await save(page,'Uploaded Games');const detail=await editable(page.request,'recommendations',row.id);expect(detail.mediaIds).toEqual(uploaded);expect(detail.gamePresentation.coverMediaId).toBe(uploaded[0]);expect(detail.gamePresentation.images.map((x:any)=>x.mediaId)).toEqual(uploaded);await publish(page.request,list,row);const anon=await browser.newContext({baseURL:fixture.origin}),foreign=await browser.newContext({baseURL:fixture.origin});try{await cookies(foreign,fixture.personas.ownerB);for(const id of uploaded){const response=await anon.request.get(`${base}/media/${id}/content`);expect(response.status()).toBe(200);expect(await response.body()).toEqual(png);}const other=await createList(foreign.request,'Foreign attachment'),e=await command(foreign.request,'post','/entities/resolve',{kind:'manual',category:'games',details:{title:'Foreign'}});const denied=await command(foreign.request,'post','/recommendations',{category:'games',collectionId:other.id,expectedCollectionRevision:other.revision,entityId:(await e.json()).entity.id,publicationState:'draft',mediaIds:uploaded});expect(denied.status()).toBe(422);}finally{await anon.close();await foreign.close();}
});

test('Games manual: provider unavailable preserves draft and forbids browser credential authority',async({page})=>{
 await signIn(page);const bad=monitor(page),list=await createList(page.request,'Unavailable provider');await form(page,list);await page.getByLabel('Game title',{exact:true}).fill('Preserved manual draft');await page.getByRole('combobox',{name:'Your rating',exact:true}).selectOption('9');await page.locator('[contenteditable=true]').fill('Preserved thoughts');await page.getByLabel('Search for a game',{exact:true}).fill('Halo');const catalog=page.waitForResponse(r=>new URL(r.url()).pathname===`${base}/catalog/games`);await page.getByRole('button',{name:'Search',exact:true}).click();const response=await catalog;expect(response.status()).toBe(503);expect((await response.json()).error.code).toBe('PROVIDER_UNAVAILABLE');await expect(page.getByLabel('Game title',{exact:true})).toHaveValue('Preserved manual draft');await expect(page.getByRole('combobox',{name:'Your rating',exact:true})).toHaveValue('9');await expect(page.locator('[contenteditable=true]')).toContainText('Preserved thoughts');expect(bad).toEqual([]);expect(await page.evaluate(()=>Object.keys(localStorage).some(key=>/igdb|twitch|client_secret/i.test(key)))).toBe(false);
});

test('Games manual: anonymous category and list continuation reveal later rows and terminal state',async({page})=>{
 const owner=fixture.personas.ownerB;await page.goto(`/${owner.handle}/games/seed-list-0`);await continueVisible(page,'Load more games','ownerB seed game 0-29');const prefix=`${base}/profiles/${owner.handle}/recommendations/games`;const rows=await complete(page.request,prefix+'/seed-list-0','recommendations');expect(rows).toHaveLength(30);expect(new Set(rows.map(x=>x.id)).size).toBe(30);const lists=await complete(page.request,prefix,'gameLists');expect(lists.length).toBeGreaterThanOrEqual(14);await page.goto(`/${owner.handle}/games`);await continueVisible(page,'Load more game lists','ownerB seed list 13');expect((await page.request.get(prefix+'?cursor=o0')).status()).toBe(400);
});


async function control(api:APIRequestContext,action:string){const response=await api.post('/api/__games-fixture/control',{headers:{Origin:fixture.origin,'X-Games-Fixture-Capability':fixture.controlCapability},data:{action}});expect(response.status()).toBe(200);return response.json();}
async function account(api:APIRequestContext){const response=await api.get(`${base}/me`);expect(response.status()).toBe(200);return (await response.json()).account;}
async function profileChange(api:APIRequestContext,patch:Record<string,unknown>){const current=await account(api);expect((await command(api,'patch','/account',{expectedRevision:current.revision,...patch})).status()).toBe(200);}

test('Games manual: ancestor hide archive and suspension deny fresh and inflight public bytes',async({page,browser})=>{
 await signIn(page);const list=await createList(page.request,'Actual byte privacy');const upload=await page.request.post(`${base}/media`,{headers:{Origin:fixture.origin,'Content-Type':'image/png','X-Media-Purpose':'recommendation','X-File-Name':'privacy.png'},data:png});expect(upload.status()).toBe(201);const media=(await upload.json()).media,row=await manual(page.request,list,'Private bytes',[media.id]);await publish(page.request,list,row);const anon=await browser.newContext({baseURL:fixture.origin});try{
  expect((await anon.request.get(media.url)).status()).toBe(200);expect((await anon.request.post('/api/__games-fixture/control',{data:{action:'arm-storage'}})).status()).toBe(404);expect((await page.request.post('/api/__games-fixture/control',{headers:{Origin:fixture.origin,'X-Games-Fixture-Capability':'wrong'},data:{action:'arm-storage'}})).status()).toBe(404);expect((await page.request.post('/api/__games-fixture/control',{headers:{Origin:'https://foreign.invalid','X-Games-Fixture-Capability':fixture.controlCapability},data:{action:'arm-storage'}})).status()).toBe(404);expect((await page.request.post('/api/__games-fixture/control',{headers:{Origin:fixture.origin,'X-Games-Fixture-Capability':fixture.controlCapability},data:{action:'suspend-ownerA',accountId:randomUUID()}})).status()).toBe(422);
  for(const gate of ['account','category','list','recommendation'] as const){
   await control(page.request,'arm-storage');const pending=anon.request.get(media.url);await expect.poll(async()=>Boolean((await control(page.request,'storage-state')).entered)).toBe(true);
   if(gate==='account')await profileChange(page.request,{publicProfile:false});
   else if(gate==='category'){const current=await account(page.request);await profileChange(page.request,{categories:current.categories.map((c:any)=>({...c,...(c.category==='games'?{isPublic:false}:{})}))});}
   else {const kind=gate==='list'?'collections':'recommendations',id=gate==='list'?list.id:row.id,observed=await editable(page.request,kind,id);expect((await command(page.request,'patch',`/${kind}/${id}`,{expectedRevision:observed.revision,...(gate==='list'?{visibility:'private'}:{publicationState:'draft'})})).status()).toBe(200);}
   await control(page.request,'release-storage');expect((await pending).status()).toBe(404);expect((await anon.request.head(media.url,{headers:{Range:'bytes=0-1','If-None-Match':'"warm"'}})).status()).toBe(404);
   if(gate==='account')await profileChange(page.request,{publicProfile:true});else if(gate==='category'){const current=await account(page.request);await profileChange(page.request,{categories:current.categories.map((c:any)=>({...c,...(c.category==='games'?{isPublic:true}:{})}))});}else await publish(page.request,list,row);
   expect((await anon.request.get(media.url)).status()).toBe(200);
  }
  await control(page.request,'suspend-ownerA');expect((await anon.request.get(media.url)).status()).toBe(404);await control(page.request,'restore-ownerA');expect((await anon.request.get(media.url)).status()).toBe(200);
  expect((await command(page.request,'delete',`/recommendations/${row.id}`,{expectedRevision:(await editable(page.request,'recommendations',row.id)).revision})).status()).toBe(200);expect((await anon.request.get(media.url)).status()).toBe(404);
  const surviving=await manual(page.request,list,'List archive boundary',[media.id]);await publish(page.request,list,surviving);expect((await anon.request.get(media.url)).status()).toBe(200);expect((await command(page.request,'delete',`/collections/${list.id}`,{expectedRevision:(await editable(page.request,'collections',list.id)).revision})).status()).toBe(200);expect((await anon.request.get(media.url)).status()).toBe(404);
 }finally{await control(page.request,'release-storage');await control(page.request,'restore-ownerA');await anon.close();}
});

test('Games manual: two anonymous contexts and username transition never reuse private or late rows',async({page,browser})=>{
 await signIn(page);const owner=fixture.personas.ownerA,other=fixture.personas.ownerB,left=await browser.newContext({baseURL:fixture.origin}),right=await browser.newContext({baseURL:fixture.origin});const changed=owner.handle+'next';let release:(()=>void)|undefined;try{
 const a=await left.newPage(),b=await right.newPage();await Promise.all([a.goto(`/${owner.handle}/games`),b.goto(`/${other.handle}/games`)]);await expect(a.getByText('ownerA seed game 0-0',{exact:true}).first()).toBeVisible();await expect(b.getByText('ownerB seed game 0-0',{exact:true}).first()).toBeVisible();expect((await left.cookies()).length).toBe(0);expect((await right.cookies()).length).toBe(0);
 const shellPath=`${base}/profiles/${owner.handle}`;expect((await left.request.get(shellPath)).status()).toBe(200);await profileChange(page.request,{publicProfile:false});expect((await left.request.get(shellPath)).status()).toBe(404);expect((await right.request.get(`${base}/profiles/${owner.handle}/recommendations/games`)).status()).toBe(404);await profileChange(page.request,{publicProfile:true});
 let entered:(()=>void)|undefined;const held=new Promise<void>(done=>{entered=done;}),settled=new Promise<void>(done=>{release=done;});await a.route(`**/api/explorers/v1/profiles/${owner.handle}/recommendations/games*`,async route=>{const response=await route.fetch();entered?.();await settled;await route.fulfill({response}).catch(()=>{});});
 await a.evaluate(path=>{history.pushState(null,'',path);dispatchEvent(new PopStateEvent('popstate'));},`/${other.handle}/games`);await expect(a.getByText('ownerB seed game 0-0',{exact:true}).first()).toBeVisible();await a.evaluate(path=>{history.pushState(null,'',path);dispatchEvent(new PopStateEvent('popstate'));},`/${owner.handle}/games`);await held;await profileChange(page.request,{handle:changed});await a.evaluate(path=>{history.pushState(null,'',path);dispatchEvent(new PopStateEvent('popstate'));},`/${other.handle}/games`);release?.();await expect(a.getByText('ownerB seed game 0-0',{exact:true}).first()).toBeVisible();await expect(a.getByText('ownerA seed game 0-0',{exact:true})).toHaveCount(0);expect((await left.request.get(`${base}/profiles/${owner.handle}/recommendations/games`)).status()).toBe(404);expect((await left.request.get(`${base}/profiles/${changed}/recommendations/games`)).status()).toBe(200);await b.reload();await expect(b.getByText('ownerB seed game 0-0',{exact:true}).first()).toBeVisible();
 }finally{release?.();await profileChange(page.request,{handle:owner.handle});await left.close();await right.close();}
});

test('Games manual: account and route changes fence every deferred save continuation',async({page})=>{
 await signIn(page);for(const boundary of ['route','account'] as const){
 const list=await createList(page.request,'Fence '+boundary);await form(page,list);await page.getByLabel('Game title',{exact:true}).fill('Deferred '+boundary);let entered:(()=>void)|undefined,release:(()=>void)|undefined;const started=new Promise<void>(done=>{entered=done;}),gate=new Promise<void>(done=>{release=done;});let recommendations=0;const onRequest=(r:any)=>{if(r.method()==='POST'&&new URL(r.url()).pathname===`${base}/recommendations`)recommendations++;};page.on('request',onRequest);
 const selector='**/api/explorers/v1/entities/resolve';await page.route(selector,async route=>{const response=await route.fetch();expect(response.status()).toBe(200);entered?.();await gate;await route.fulfill({response}).catch(()=>{});});try{
 await page.getByRole('button',{name:'Save game',exact:true}).click();await started;if(boundary==='account'){await page.context().clearCookies();await cookies(page.context(),fixture.personas.ownerB);}await page.goto('/recommendations/games');release?.();await page.waitForLoadState('networkidle',{timeout:15000});await expect(page.getByRole('button',{name:'New List',exact:true}).filter({visible:true}).first()).toBeVisible();await expect(page.getByText('Game saved',{exact:true})).toHaveCount(0);expect(recommendations).toBe(0);
 }finally{release?.();await page.unroute(selector);page.off('request',onRequest);await page.context().clearCookies();await cookies(page.context(),fixture.personas.ownerA);}
 const all=await page.request.get(`${base}/recommendations?category=games&collectionId=${list.id}&limit=100`);expect(all.status()).toBe(200);expect((await all.json()).items).toHaveLength(0);
 }
});
