import type {EditableOwnerRecommendation,OwnerCollectionDto,OwnerMembershipDto} from '../../../../../tunes/shared/explorersOwnerContentContract';
import {manualGamePresentationSchema} from '../../../../../tunes/shared/explorersGameOwnerContract';
import type {GameList,RecommendedGame} from '../types';
import type {CompleteGamesOwnerContent} from './gamesClient';
import {ExplorersApiError,type RecommendationObservation,assertCompleteMyCategoryContent} from '../../../lib/explorersApiClient';
type Pin={recommendationId:string;collectionId:string;position:number};
export function gameViewModel(detail:Readonly<EditableOwnerRecommendation>,membership:Readonly<OwnerMembershipDto>,pin?:Readonly<Pin>):RecommendedGame{
 if(detail.category!=='games'||detail.entity.kind!=='game'||detail.id!==membership.recommendationId)throw new ExplorersApiError(409,'CONFLICT','Games detail identity changed');
 const parsed=manualGamePresentationSchema.safeParse(detail.gamePresentation);if(!parsed.success)throw new ExplorersApiError(503,'PROVIDER_UNAVAILABLE','Games presentation is unavailable');
 const media=parsed.data; const selectedPin=pin?.recommendationId===membership.recommendationId&&pin.collectionId===membership.collectionId?pin:undefined;
 return {documentId:detail.id,entity_id:detail.entityId,igdb_id:null,igdb_slug:null,title:detail.displayTitle??'Untitled game',cover_url:media.images[0]?.url??null,cover_url_large:media.images[0]?.url??null,igdb_image_id:null,summary:null,release_date:null,release_year:null,igdb_rating:null,igdb_rating_count:null,genres:null,platforms:null,developer:null,publisher:null,game_modes:null,screenshot_ids:null,igdb_url:null,user_recommendation_note:detail.note?.html??'',user_rating:detail.userRating,is_pinned:!!selectedPin,pin_order:selectedPin?.position??null,display_order:membership.displayOrder,media_details:null,game_list:{documentId:membership.collectionId,List_Name:'',slug:''},game_categories:null,Media:media.images.map(image=>({documentId:image.mediaId,url:image.url}))};
}
export function collectionViewModel(collection:Readonly<OwnerCollectionDto>,games:RecommendedGame[],username=''):GameList{return {documentId:collection.id,List_Name:collection.title,list_description:collection.description,slug:collection.slug,Visibility:collection.visibility==='public'&&collection.publicationState==='published',cover_image:collection.coverMediaId?{url:`/api/explorers/v1/media/${collection.coverMediaId}/content`,alternativeText:null}:null,display_order:collection.displayOrder,top_picks_heading:collection.heading,recommended_games:games.map(game=>({...game,game_list:{documentId:collection.id,List_Name:collection.title,slug:collection.slug}})),account:{documentId:collection.accountId,username}};}
export type GameOwnerView={lists:GameList[]};
export const gamesViewModel={complete(observed:CompleteGamesOwnerContent,details:ReadonlyMap<string,RecommendationObservation>,username=''):Readonly<GameOwnerView>{
 assertCompleteMyCategoryContent(observed);if(observed.category!=='games')throw new ExplorersApiError(409,'CONFLICT','Games category required');
 return {lists:observed.collections.map(collection=>collectionViewModel(collection,observed.memberships.filter(member=>member.collectionId===collection.id&&!member.collectionArchived&&!member.recommendationArchived).sort((a,b)=>a.displayOrder-b.displayOrder||a.recommendationId.localeCompare(b.recommendationId)).map(member=>{const detail=details.get(member.recommendationId);if(!detail||detail.detail.revision!==observed.recommendations.find(item=>item.id===member.recommendationId)?.revision||detail.detail.categoryRevision!==observed.revision)throw new ExplorersApiError(409,'CONFLICT','Games changed while loading');return gameViewModel(detail.detail,member,observed.topPicks?.find(pin=>pin.recommendationId===member.recommendationId&&pin.collectionId===member.collectionId));}),username))};
}};
