import {beforeEach,it,expect,vi} from 'vitest';import {GamesClient} from '../gamesClient';import {readGamesOwnerContent} from '../explorersAdapter';import useAuthStore from '../../../../store/store';
vi.mock('../gamesClient',()=>({GamesClient:{readCompleteOwner:vi.fn(),observeRecommendation:vi.fn()}}));vi.mock('../gamesViewModel',()=>({gamesViewModel:{complete:vi.fn(()=>({lists:[]}))}}));
beforeEach(()=>{vi.clearAllMocks();useAuthStore.setState({accountId:'owner',generation:1});});
it('never exposes partial details or a changed final category observation',async()=>{const observed={revision:'1',pinRevision:1,recommendations:[{id:'rec',revision:1}]} as never;vi.mocked(GamesClient.readCompleteOwner).mockResolvedValueOnce(observed).mockResolvedValueOnce({...observed as any,revision:'2'});vi.mocked(GamesClient.observeRecommendation).mockResolvedValue({detail:{revision:1,categoryRevision:'1'}} as never);await expect(readGamesOwnerContent()).rejects.toMatchObject({status:409});});
it('rejects owner epoch drift during detail completion',async()=>{vi.mocked(GamesClient.readCompleteOwner).mockResolvedValue({revision:'1',pinRevision:1,recommendations:[{id:'rec',revision:1}]} as never);vi.mocked(GamesClient.observeRecommendation).mockImplementation(async()=>{useAuthStore.setState({generation:2});return {detail:{revision:1,categoryRevision:'1'}} as never;});await expect(readGamesOwnerContent()).rejects.toMatchObject({status:409});});
it('holds a four-reader maximum and authentic final observation for complete hydration',async()=>{const recommendations=Array.from({length:12},(_,n)=>({id:String(n),revision:1})),observed={revision:'1',pinRevision:1,recommendations} as never;vi.mocked(GamesClient.readCompleteOwner).mockResolvedValue(observed);let active=0,max=0;vi.mocked(GamesClient.observeRecommendation).mockImplementation(async()=>{active++;max=Math.max(max,active);await Promise.resolve();active--;return {detail:{revision:1,categoryRevision:'1'}} as never;});const value=await readGamesOwnerContent();expect(value.observation).toBe(observed);expect(value.details.size).toBe(12);expect(max).toBeLessThanOrEqual(4);});

// A failed worker cannot leave surviving workers claiming new detail indices.
it.each(['transport','undefined','resource-revision','category-revision','bytes'] as const)('stops future claims after %s terminal failure and preserves the first error',async mode=>{
 vi.clearAllMocks();useAuthStore.setState({accountId:'owner',generation:1});
 const observed={revision:'1',pinRevision:1,collections:[],memberships:[],topPicks:[],recommendations:Array.from({length:5},(_,n)=>({id:String(n),revision:1}))};
 vi.mocked(GamesClient.readCompleteOwner).mockResolvedValue(observed as never);
 const pending:Array<{resolve:(value:unknown)=>void;reject:(reason:unknown)=>void}>=[];
 vi.mocked(GamesClient.observeRecommendation).mockImplementation(()=>new Promise((resolve,reject)=>pending.push({resolve:resolve as (value:unknown)=>void,reject})));
 const sentinel=mode==='undefined'?undefined:{terminal:'first'};const caller=new AbortController();const removed=vi.spyOn(caller.signal,'removeEventListener');const work=readGamesOwnerContent(caller.signal);let failure:unknown;const settled=work.catch(error=>{failure=error;});
 await vi.waitFor(()=>expect(pending).toHaveLength(4));if(mode==='transport'||mode==='undefined')pending[0].reject(sentinel);else pending[0].resolve({detail:{revision:mode==='resource-revision'?2:1,categoryRevision:mode==='category-revision'?'2':'1',...(mode==='bytes'?{oversized:'x'.repeat(64*1024*1024+1)}:{})}});await settled;if(mode==='transport'||mode==='undefined')expect(failure).toBe(sentinel);else expect(failure).toMatchObject({code:mode==='bytes'?'READ_LIMIT':'CONFLICT'});const originalFailure=failure;expect(removed).toHaveBeenCalledTimes(1);const signals=vi.mocked(GamesClient.observeRecommendation).mock.calls.slice(0,4).map(call=>call[1] as AbortSignal);expect(signals.every(value=>value!==caller.signal&&value.aborted)).toBe(true);
 pending[1].resolve({detail:{revision:1,categoryRevision:'1'}});await Promise.resolve();await Promise.resolve();await Promise.resolve();
 expect(GamesClient.observeRecommendation).toHaveBeenCalledTimes(4);expect(GamesClient.readCompleteOwner).toHaveBeenCalledTimes(1);
 pending[2].reject({terminal:'late'});pending[3].resolve({detail:{revision:1,categoryRevision:'1'}});await Promise.resolve();await Promise.resolve();expect(failure).toBe(originalFailure);
});


it('does not acquire any category transport for a preaborted caller and removes its listener',async()=>{vi.clearAllMocks();const caller=new AbortController();caller.abort();const remove=vi.spyOn(caller.signal,'removeEventListener');await expect(readGamesOwnerContent(caller.signal)).rejects.toMatchObject({name:'AbortError'});expect(GamesClient.observeRecommendation).not.toHaveBeenCalled();expect(remove).toHaveBeenCalledTimes(1);});

it('forwards caller cancellation to admitted siblings and prevents late new claims',async()=>{
 vi.clearAllMocks();useAuthStore.setState({accountId:'owner',generation:1});const observed={revision:'1',pinRevision:1,collections:[],memberships:[],topPicks:[],recommendations:Array.from({length:5},(_,n)=>({id:String(n),revision:1}))};vi.mocked(GamesClient.readCompleteOwner).mockResolvedValue(observed as never);
 const pending:Array<(v:unknown)=>void>=[];vi.mocked(GamesClient.observeRecommendation).mockImplementation(()=>new Promise(resolve=>pending.push(resolve as (v:unknown)=>void)));const caller=new AbortController(),remove=vi.spyOn(caller.signal,'removeEventListener');const work=readGamesOwnerContent(caller.signal);const failure=work.catch(e=>e);await vi.waitFor(()=>expect(pending).toHaveLength(4));caller.abort();expect(vi.mocked(GamesClient.observeRecommendation).mock.calls.every(call=>(call[1] as AbortSignal).aborted)).toBe(true);pending[0]({detail:{revision:1,categoryRevision:'1'}});expect(await failure).toMatchObject({name:'AbortError'});for(const resolve of pending.slice(1))resolve({detail:{revision:1,categoryRevision:'1'}});await Promise.resolve();await Promise.resolve();expect(GamesClient.observeRecommendation).toHaveBeenCalledTimes(4);expect(GamesClient.readCompleteOwner).toHaveBeenCalledTimes(1);expect(remove).toHaveBeenCalledTimes(1);
});
it('removes caller forwarding after successful complete hydration',async()=>{vi.clearAllMocks();useAuthStore.setState({accountId:'owner',generation:1});const observed={revision:'1',pinRevision:1,collections:[],memberships:[],topPicks:[],recommendations:[]};vi.mocked(GamesClient.readCompleteOwner).mockResolvedValue(observed as never);const caller=new AbortController(),remove=vi.spyOn(caller.signal,'removeEventListener');await readGamesOwnerContent(caller.signal);expect(remove).toHaveBeenCalledTimes(1);expect(GamesClient.readCompleteOwner).toHaveBeenCalledTimes(2);});
