import {randomBytes as secureRandomBytes} from 'node:crypto';
import type {Actor} from '../application/actor';
import {gameSearchInputSchema,gameExternalIdSchema,type GameProviderFacts} from '../../shared/explorersGameContract';
import {buildGameSearchQuery,buildGameResolveQuery,parseGameProviderPage,mapGameProviderFacts} from './gameCatalogContracts';
import {unavailable,busy,bounded,bindingEqual,GameCatalogFailure,LIMITS,type ActorBinding,type CatalogOptions,type GameSearchPage,type Release,type NativeOperation} from './gameCatalogTypes';
import type {GameProviderCoordinator} from './gameProviderBudget';
type Lineage={attempts:number;scans:number};
type State={binding:ActorBinding;query:string;limit:24;expires:number;offset:number;seen:string[];pending:GameProviderFacts[];done:boolean;lineage:Lineage};
type Flight=NativeOperation<GameSearchPage>&{waiters:number;custody:number;custodyChanged:()=>void};
type Entry={state:State;response?:GameSearchPage;flight?:Flight;pins:number;size:number;release:Release};
const caches=new WeakMap<GameProviderCoordinator,Map<string,Entry>>();
const cursorError=()=>new GameCatalogFailure(410,'CURSOR_EXPIRED');
const limit=()=>new GameCatalogFailure(429,'GAME_CONTINUATION_LIMIT');
const clone=<T>(v:T):T=>structuredClone(v);
type AuthorizationCustody={jobs:Promise<unknown>[];active:number;changed?:()=>void};
/** Conservative retained representation estimate; never allocates an unreserved JSON serialization. */
function sizeOf(v:unknown):number{let total=0;const stack:unknown[]=[v];while(stack.length){const value=stack.pop();total+=64;if(total>LIMITS.sessionBytes)throw busy();if(typeof value==='string')total+=value.length*2;if(value&&typeof value==='object'){for(const [key,child]of Object.entries(value)){total+=key.length*2+32;stack.push(child);}}}return total;}
export class GameCatalog {
 private readonly states:Map<string,Entry>;private readonly now:()=>number;private readonly random:(n:number)=>Uint8Array;
 constructor(private readonly options:CatalogOptions){this.now=options.coordinator.now;this.random=options.randomBytes??secureRandomBytes;let cache=caches.get(options.coordinator);if(!cache){cache=new Map();caches.set(options.coordinator,cache);}this.states=cache;if(options.callerMs!==undefined&&(!Number.isInteger(options.callerMs)||options.callerMs<1||options.callerMs>15000))throw unavailable();}
 private evict(key:string,e:Entry){this.states.delete(key);e.release();}
 private touch(key:string,e:Entry){this.states.delete(key);this.states.set(key,e);}
 private room(account:string,extra:number,bytes:number){for(const [key,e]of Array.from(this.states))if(e.state.expires<=this.now()&&!e.flight&&!e.pins)this.evict(key,e);const count=()=>Array.from(this.states.values()).filter(e=>e.state.binding.accountId===account).length;while(this.states.size+extra>LIMITS.sessions||count()+extra>LIMITS.accountSessions||this.options.coordinator.snapshot().memory+bytes>LIMITS.memory){const accountFull=count()+extra>LIMITS.accountSessions;const victim=Array.from(this.states).find(([,e])=>!e.flight&&!e.pins&&(!accountFull||e.state.binding.accountId===account));if(!victim)throw busy();this.evict(victim[0],victim[1]);}}
 private signal(parent?:AbortSignal){const c=new AbortController();const abort=()=>c.abort();parent?.addEventListener('abort',abort,{once:true});if(parent?.aborted)c.abort();const timer=setTimeout(abort,this.options.callerMs??LIMITS.callerMs);return {signal:c.signal,abort,cleanup:()=>{clearTimeout(timer);parent?.removeEventListener('abort',abort);}};}
 private async authorize(actor:Actor,expected:ActorBinding|undefined,signal:AbortSignal,pending:AuthorizationCustody){const job=this.options.authorize(actor);pending.jobs.push(job);pending.active++;const done=()=>{pending.active--;pending.changed?.();};void job.then(done,done);const binding=await bounded(job,signal);if(binding.accountId!==actor.accountId||binding.userId!==actor.userId||typeof binding.credentialKey!=='string'||!binding.credentialKey||typeof binding.authorizationEpoch!=='string'||!binding.authorizationEpoch||expected&&!bindingEqual(expected,binding))throw cursorError();return {...binding};}
 private async join(flight:Flight,actor:Actor,binding:ActorBinding,signal:AbortSignal,pending:AuthorizationCustody):Promise<GameSearchPage>{if(signal.aborted)throw unavailable();flight.waiters++;flight.custody++;let attached=true;const detach=()=>{if(attached){attached=false;flight.waiters--;if(!flight.waiters)flight.cancel();}};signal.addEventListener('abort',detach,{once:true});try{const result=await bounded(flight.outcome,signal);await this.authorize(actor,binding,signal,pending);if(result.expiresAt<=this.now())throw cursorError();const release=this.options.coordinator.reserveMemory(sizeOf(result));try{return clone(result);}finally{release();}}finally{signal.removeEventListener('abort',detach);detach();void Promise.all(pending.jobs.map(x=>x.then(()=>undefined,()=>undefined))).then(()=>{flight.custody--;flight.custodyChanged();});}}
 async search(actor:Actor,input:unknown,parent?:AbortSignal):Promise<GameSearchPage>{const parsed=gameSearchInputSchema.safeParse(input);if(!parsed.success)throw new GameCatalogFailure(422,'INVALID_INPUT');const p=parsed.data;const releaseCaller=this.options.coordinator.reserveCaller();const caller=this.signal(parent);const pending:AuthorizationCustody={jobs:[],active:0};let wait:Promise<void>|undefined;let entry:Entry|undefined;let acquiredPin=false;const work=(async()=>{
  const binding=await this.authorize(actor,undefined,caller.signal,pending);
  if(p.cursor){entry=this.states.get(p.cursor);if(!entry||entry.state.expires<=this.now()||!bindingEqual(entry.state.binding,binding)||entry.state.query!==p.query||entry.state.limit!==p.limit)throw cursorError();this.touch(p.cursor,entry);entry.pins++;acquiredPin=true;if(entry.response){this.options.coordinator.rate(binding.accountId);await this.authorize(actor,binding,caller.signal,pending);if(entry.state.expires<=this.now())throw cursorError();const n=sizeOf(entry.response);const r=this.options.coordinator.reserveMemory(n);try{return clone(entry.response);}finally{r();}}if(entry.flight){wait=entry.flight.settled;return this.join(entry.flight,actor,binding,caller.signal,pending);}}
  this.options.coordinator.rate(binding.accountId);const releaseAccount=this.options.coordinator.reserveAccount(binding.accountId);let releaseStage:Release=()=>{};try{this.room(binding.accountId,0,LIMITS.catalogMemory+3*LIMITS.sessionBytes);releaseStage=this.options.coordinator.reserveMemory(LIMITS.catalogMemory+3*LIMITS.sessionBytes);}catch(error){releaseAccount();throw error;}
  const execution=this.signal();const executionAuthority:AuthorizationCustody={jobs:[],active:0};let operation!:Flight;const owned:Promise<unknown>[]=[];let executionDone=false;let nativePending=0;const releaseExecution=()=>{if(executionDone&&!nativePending&&!executionAuthority.active&&!operation.custody){execution.cleanup();releaseStage();releaseAccount();if(entry&&entry.flight===operation)entry.flight=undefined;}};
  executionAuthority.changed=releaseExecution;const own=(promise:Promise<unknown>)=>{nativePending++;owned.push(promise);void promise.then(()=>{nativePending--;releaseExecution();},()=>{nativePending--;releaseExecution();});};
  const state:State=entry?.state??{binding,query:p.query,limit:24,expires:this.now()+LIMITS.ttl,offset:0,seen:[],pending:[],done:false,lineage:{attempts:0,scans:0}};
  const execute=(async()=>{const next:State={...clone(state),lineage:state.lineage};const items:GameProviderFacts[]=[];let callPages=0;
   while(items.length<24){while(next.pending.length&&items.length<24){const candidate=next.pending.shift()!;if(next.seen.includes(candidate.externalId))continue;next.seen.push(candidate.externalId);items.push(candidate);}if(items.length===24||next.done||callPages===LIMITS.callPages)break;if(next.lineage.attempts>=LIMITS.pages)throw limit();
    await this.authorize(actor,binding,execution.signal,executionAuthority);if(next.expires<=this.now())throw cursorError();
    const native=this.options.transport.catalog(buildGameSearchQuery(p,next.offset),execution.signal,{beforeStart:async()=>{await this.authorize(actor,binding,execution.signal,executionAuthority);if(next.expires<=this.now())throw cursorError();},onStart:()=>{if(next.lineage.attempts>=LIMITS.pages)throw limit();next.lineage.attempts++;callPages++;}});own(native.settled);execution.signal.addEventListener('abort',native.cancel,{once:true});let raw:unknown;try{raw=await bounded(native.outcome,execution.signal);}finally{execution.signal.removeEventListener('abort',native.cancel);}
    await this.authorize(actor,binding,execution.signal,executionAuthority);if(next.expires<=this.now())throw cursorError();if(Array.isArray(raw)){next.lineage.scans+=raw.length;if(next.lineage.scans>LIMITS.scans)throw limit();}
    let rows;try{rows=parseGameProviderPage(raw);}catch{throw new GameCatalogFailure(502,'PROVIDER_INVALID_RESPONSE');}if(next.lineage.attempts===LIMITS.pages&&rows.length)throw limit();if(!rows.length){next.done=true;continue;}
    next.offset+=rows.length;try{next.pending=rows.map(r=>mapGameProviderFacts(r,String(r.id),this.now()));}catch{throw new GameCatalogFailure(502,'PROVIDER_INVALID_RESPONSE');}sizeOf(next);
   }
   await this.authorize(actor,binding,execution.signal,executionAuthority);if(execution.signal.aborted||!operation.waiters)throw unavailable();if(next.expires<=this.now())throw cursorError();
   const more=next.pending.length||!next.done;const token=more?Buffer.from(this.random(24)).toString('base64url'):null;const response:GameSearchPage={version:'explorers-game-candidates/v1',items,nextCursor:token,expiresAt:next.expires};const responseBytes=sizeOf(response);if(entry&&entry.size+responseBytes>LIMITS.sessionBytes)throw busy();const newBytes=token?sizeOf(next):0;
   this.room(binding.accountId,token?1:0,newBytes+responseBytes);let releaseNext:Release=()=>{},releaseReceipt:Release=()=>{};try{if(token)releaseNext=this.options.coordinator.reserveMemory(newBytes);if(entry)releaseReceipt=this.options.coordinator.reserveMemory(responseBytes);if(token){if(this.states.has(token))throw busy();this.states.set(token,{state:next,pins:0,size:newBytes,release:releaseNext});}if(entry){const oldRelease=entry.release;entry.response=clone(response);entry.size+=responseBytes;entry.release=()=>{oldRelease();releaseReceipt();};}return clone(response);}catch(error){releaseNext();releaseReceipt();throw error;}
  })();const settled=execute.then(()=>undefined,()=>undefined).then(()=>Promise.all([...owned,...executionAuthority.jobs].map(x=>x.then(()=>undefined,()=>undefined))).then(()=>undefined));operation={outcome:execute,settled,waiters:0,custody:0,custodyChanged:releaseExecution,cancel:()=>{(execution as {abort:()=>void}).abort();}};if(entry)entry.flight=operation;wait=settled;void execute.then(()=>{executionDone=true;releaseExecution();},()=>{executionDone=true;releaseExecution();});return this.join(operation,actor,binding,caller.signal,pending);
 })();
 const settle=work.then(()=>undefined,()=>undefined).then(async()=>{await wait;await Promise.all(pending.jobs.map(x=>x.then(()=>undefined,()=>undefined)));}).finally(()=>{if(entry&&acquiredPin)entry.pins--;caller.cleanup();releaseCaller();});void settle.catch(()=>{});return bounded(work,caller.signal);
 }
 async resolve(actor:Actor,id:string,parent?:AbortSignal):Promise<GameProviderFacts>{if(!gameExternalIdSchema.safeParse(id).success)throw new GameCatalogFailure(422,'INVALID_INPUT');const releaseCaller=this.options.coordinator.reserveCaller(),caller=this.signal(parent);const pending:AuthorizationCustody={jobs:[],active:0};let releaseAccount:Release=()=>{},releaseMemory:Release=()=>{},native:NativeOperation<unknown>|undefined;
  const work=(async()=>{const binding=await this.authorize(actor,undefined,caller.signal,pending);this.options.coordinator.rate(binding.accountId);releaseAccount=this.options.coordinator.reserveAccount(binding.accountId);releaseMemory=this.options.coordinator.reserveMemory(LIMITS.catalogMemory);await this.authorize(actor,binding,caller.signal,pending);native=this.options.transport.catalog(buildGameResolveQuery(id),caller.signal,{beforeStart:async()=>{await this.authorize(actor,binding,caller.signal,pending);},onStart:()=>{}});caller.signal.addEventListener('abort',native.cancel,{once:true});const raw=await bounded(native.outcome,caller.signal);await this.authorize(actor,binding,caller.signal,pending);let rows;try{rows=parseGameProviderPage(raw);if(rows.length!==1)throw unavailable();return mapGameProviderFacts(rows[0],id,this.now());}catch{throw new GameCatalogFailure(502,'PROVIDER_INVALID_RESPONSE');}})();
  void work.then(()=>undefined,()=>undefined).then(async()=>{await native?.settled;await Promise.all(pending.jobs.map(x=>x.then(()=>undefined,()=>undefined)));}).finally(()=>{if(native)caller.signal.removeEventListener('abort',native.cancel);releaseMemory();releaseAccount();releaseCaller();caller.cleanup();});return bounded(work,caller.signal);
 }
}
